### ISSUE TITLE
PNG Gdrive Link dead

### ISSUE THREAD

**Issue by h2jaafar** [TeaganLi/HouseExpo#4]
Hello, 

In the readme file it mentions the Google Drive link to the dataset images as PNG files (https://drive.google.com/file/d/12CU51Fhi-_WubsPUsq5KCijfucW5HG7G/view?usp=sharing)

The link doesn't seem to exist. If there is another link, that would be appreciated. Thanks

**Comment by TeaganLi** [comment]
Sorry for the broken link. A new link to the png files has been updated. Feel free to check it out.

**Comment by h2jaafar** [comment]
Thank you!
